# Generated by Django 2.2 on 2020-10-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('image_1', models.ImageField(help_text='Primary', upload_to='product_pics/')),
                ('image_2', models.ImageField(upload_to='product_pics/')),
                ('image_3', models.ImageField(upload_to='product_pics/')),
                ('image_4', models.ImageField(upload_to='product_pics/')),
                ('image_5', models.ImageField(upload_to='product_pics/')),
                ('image_6', models.ImageField(upload_to='product_pics/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
    ]
