# Generated by Django 2.2 on 2020-10-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
